"""
Core routes blueprint for Voyagr.

Contains:
- Index page
- Config endpoint
- Monitoring dashboard
- Manifest and service worker
- Digital Asset Links (TWA verification)
- Privacy policy (required by Google Play)
"""

import json
import os
from typing import Optional

from flask import Blueprint, jsonify, render_template, current_app, Response, make_response

from voyagr.discoverability import block_search_indexing
from voyagr.ga4 import template_kwargs as ga4_template_kwargs
from voyagr.index_page_context import build_index_template_kwargs, tomtom_client_surface
from voyagr.seo import (
    render_empty_sitemap_xml,
    render_llms_full_txt,
    render_llms_txt,
    render_robots_txt,
    render_sitemap_xml,
)
from voyagr.utils.admin_auth import require_admin_if_configured

core_bp = Blueprint('core', __name__)


@core_bp.route('/')
def index():
    """Render the main application page."""
    html = render_template('index.html', **build_index_template_kwargs())
    response = make_response(html)
    # Shell HTML is server-rendered (wake/Sherpa flags, keys). Do not cache at CDN or browser.
    response.headers['Cache-Control'] = 'no-store, no-cache, must-revalidate, max-age=0'
    response.headers['Pragma'] = 'no-cache'
    response.headers['Expires'] = '0'
    return response


@core_bp.route('/api/config')
def get_config():
    """Return client-side configuration including API keys.
    This endpoint bypasses HTML caching issues."""
    stripe_key = os.getenv('STRIPE_SECRET_KEY', '').strip()
    sub_price = os.getenv('STRIPE_SUBSCRIPTION_PRICE_ID', '').strip() or os.getenv(
        'STRIPE_DONATE_PRICE_ID', ''
    ).strip()
    trial_raw = os.getenv('STRIPE_SUBSCRIPTION_TRIAL_DAYS', '').strip()
    trial_days_out: Optional[int] = None
    if trial_raw.isdigit():
        tv = int(trial_raw)
        if tv > 0:
            trial_days_out = tv
    _tt_key, _tt_proxy = tomtom_client_surface()
    response = jsonify({
        'tomtom_api_key': _tt_key,
        'tomtom_traffic_tile_proxy': _tt_proxy,
        'openweathermap_api_key': os.getenv('OPENWEATHERMAP_API_KEY', ''),
        # Supabase (public)
        'supabase_url': os.getenv('SUPABASE_URL', ''),
        'supabase_anon_key': os.getenv('SUPABASE_ANON_KEY', ''),
        # Auth behavior
        'require_login': os.getenv('REQUIRE_LOGIN', 'false').lower() == 'true',
        # Discoverability (client may adjust UI; enforcement is server headers + robots.txt)
        'block_search_indexing': block_search_indexing(),
        # Stripe = subscription (Payment Link or Checkout); BMC / Patreon = one-off tips
        'stripe_payment_link_url': os.getenv('VOYAGR_STRIPE_PAYMENT_LINK_URL', '').strip(),
        'buy_me_a_coffee_url': os.getenv('VOYAGR_BUYMEACOFFEE_URL', '').strip(),
        'patreon_url': os.getenv('VOYAGR_PATREON_URL', '').strip(),
        'stripe_subscription_checkout_available': bool(stripe_key and sub_price),
        # Deprecated alias (same flag); remove when all clients updated
        'stripe_checkout_available': bool(stripe_key and sub_price),
        # Shown after sign-in for the Stripe trial gate; Payment Link trials can also be set in Stripe Dashboard.
        # Example: STRIPE_SUBSCRIPTION_TRIAL_DAYS=7 with Checkout — trial_period_days is set on subscription_data.
        'stripe_subscription_trial_days': trial_days_out,
        # Optional notice (e.g. "UK only") — set VOYAGR_SERVICE_REGION_NOTE on the server
        'service_region_note': os.getenv('VOYAGR_SERVICE_REGION_NOTE', '').strip(),
        # When true, routes using require_promo_premium_if_enforced reject users without promo trial/lifetime
        'promo_premium_enforcement': os.getenv('VOYAGR_ENFORCE_PROMO_PREMIUM', '').strip().lower()
        in ('1', 'true', 'yes'),
        'success': True
    })
    # Prevent caching
    response.headers['Cache-Control'] = 'no-store, no-cache, must-revalidate, max-age=0'
    response.headers['Pragma'] = 'no-cache'
    response.headers['Expires'] = '0'
    return response


@core_bp.route('/robots.txt')
def robots_txt():
    """Crawler policy.

    When VOYAGR_BLOCK_SEARCH_INDEXING is on, disallow everything. Otherwise allow
    crawling of public pages, disallow API + monitoring surfaces, and advertise
    the sitemap. Body is generated by voyagr.seo so it stays in sync with the
    HTML <meta robots> tag and the sitemap contents.
    """
    body = render_robots_txt(allow=not block_search_indexing())
    response = Response(body, mimetype='text/plain; charset=utf-8')
    response.headers['Cache-Control'] = 'public, max-age=3600'
    return response


@core_bp.route('/sitemap.xml')
def sitemap_xml():
    """Search-engine sitemap. Empty (but valid) when indexing is blocked."""
    if block_search_indexing():
        body = render_empty_sitemap_xml()
    else:
        body = render_sitemap_xml()
    response = Response(body, mimetype='application/xml; charset=utf-8')
    response.headers['Cache-Control'] = 'public, max-age=3600'
    return response


@core_bp.route('/llms.txt')
def llms_txt():
    """llms.txt / llmstxt.org — concise GEO + LLMO context for AI crawlers.

    Provides a clean markdown summary (features, FAQ, canonical links) so
    generative engines cite accurate facts instead of scraped JS-rendered HTML.
    Falls back to a minimal opt-out notice when indexing is blocked.
    """
    body = render_llms_txt(allow=not block_search_indexing())
    response = Response(body, mimetype='text/plain; charset=utf-8')
    response.headers['Cache-Control'] = 'public, max-age=3600'
    return response


@core_bp.route('/llms-full.txt')
def llms_full_txt():
    """Extended LLMO context — entity summary, use cases, citation guidance + shared FAQ."""
    body = render_llms_full_txt(allow=not block_search_indexing())
    response = Response(body, mimetype='text/plain; charset=utf-8')
    response.headers['Cache-Control'] = 'public, max-age=3600'
    return response


@core_bp.route('/monitoring')
@require_admin_if_configured
def monitoring_dashboard():
    """Monitoring dashboard for routing engines."""
    return render_template('monitoring_dashboard.html', **ga4_template_kwargs())


@core_bp.route('/manifest.json')
def manifest():
    """Serve the PWA manifest file."""
    manifest_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), 'manifest.json')
    with open(manifest_path, 'r', encoding='utf-8') as f:
        return jsonify(json.load(f))


@core_bp.route('/favicon.ico')
def favicon():
    """Redirect legacy /favicon.ico requests to the SVG app icon.

    Modern browsers use <link rel="icon"> tags, but crawlers, bookmark tools,
    and some platform scrapers still probe /favicon.ico directly. Point them
    at the current app icon so we don't 404 and so the branding stays consistent.
    """
    from flask import redirect
    return redirect('/static/images/icons/icon.svg', code=302)


@core_bp.route('/service-worker.js')
def service_worker():
    """Serve the service worker script."""
    sw_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), 'service-worker.js')
    with open(sw_path, 'r', encoding='utf-8') as f:
        response = current_app.make_response(f.read())
        response.headers['Content-Type'] = 'application/javascript'
        response.headers['Service-Worker-Allowed'] = '/'
        response.headers['Cache-Control'] = 'no-cache, no-store, must-revalidate'
        response.headers['Pragma'] = 'no-cache'
        return response


@core_bp.route('/.well-known/assetlinks.json')
def asset_links():
    """Serve Digital Asset Links for TWA (Trusted Web Activity) verification.

    The SHA-256 fingerprint is read from the TWA_SHA256_FINGERPRINT env var.
    Set this to the signing certificate fingerprint of your Android app
    (upload key or Play App Signing key).
    """
    fingerprint = os.getenv(
        'TWA_SHA256_FINGERPRINT',
        'REPLACE_WITH_YOUR_SHA256_FINGERPRINT'
    )
    package_name = os.getenv('TWA_PACKAGE_NAME', 'com.voyagr.app')
    asset_links = [
        {
            "relation": ["delegate_permission/common.handle_all_urls"],
            "target": {
                "namespace": "android_app",
                "package_name": package_name,
                "sha256_cert_fingerprints": [fingerprint]
            }
        }
    ]
    response = jsonify(asset_links)
    response.headers['Content-Type'] = 'application/json'
    response.headers['Cache-Control'] = 'public, max-age=3600'
    return response


@core_bp.route('/privacy')
def privacy_policy():
    """Serve the privacy policy page (required by Google Play Store)."""
    return render_template('privacy_policy.html', **ga4_template_kwargs())

